-- MySQL Script generated by MySQL Workbench
-- Tue Mar  8 10:00:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema militaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema militaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `militaria` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `militaria` ;

-- -----------------------------------------------------
-- Table `militaria`.`kategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `militaria`.`kategoria` (
  `id` INT NOT NULL,
  `nazwa` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `militaria`.`podkategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `militaria`.`podkategoria` (
  `id` INT NOT NULL,
  `nazwa` VARCHAR(50) NULL,
  `kategoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_podkategoria_kategoria1_idx` (`kategoria_id` ASC),
  CONSTRAINT `fk_podkategoria_kategoria1`
    FOREIGN KEY (`kategoria_id`)
    REFERENCES `militaria`.`kategoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `militaria`.`stan_dostepnosci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `militaria`.`stan_dostepnosci` (
  `id` INT NOT NULL,
  `nazwa` VARCHAR(45) NOT NULL,
  `ilosc` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `militaria`.`producent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `militaria`.`producent` (
  `id` INT NOT NULL,
  `nazwa` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `militaria`.`produkt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `militaria`.`produkt` (
  `id` INT NOT NULL,
  `nazwa` VARCHAR(50) NULL,
  `numer` VARCHAR(25) NULL,
  `dostepnosc` INT(11) NULL,
  `koszt` DECIMAL(19,2) NULL,
  `opis` VARCHAR(255) NULL,
  `podkategoria_id` INT NOT NULL,
  `stan_dostepnosci_id` INT NOT NULL,
  `produktcol` VARCHAR(45) NULL,
  `producent_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produkt_podkategoria_idx` (`podkategoria_id` ASC),
  INDEX `fk_produkt_stan_dostepnosci1_idx` (`stan_dostepnosci_id` ASC),
  INDEX `fk_produkt_producent1_idx` (`producent_id` ASC),
  CONSTRAINT `fk_produkt_podkategoria`
    FOREIGN KEY (`podkategoria_id`)
    REFERENCES `militaria`.`podkategoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produkt_stan_dostepnosci1`
    FOREIGN KEY (`stan_dostepnosci_id`)
    REFERENCES `militaria`.`stan_dostepnosci` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produkt_producent1`
    FOREIGN KEY (`producent_id`)
    REFERENCES `militaria`.`producent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `militaria`.`adres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `militaria`.`adres` (
  `id` INT NOT NULL,
  `wojewodztwo` VARCHAR(45) NULL,
  `miasto` VARCHAR(45) NULL,
  `ulica` VARCHAR(45) NULL,
  `numer ulicy` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `militaria`.`Paczkomaty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `militaria`.`Paczkomaty` (
  `id` INT NOT NULL,
  `kod` VARCHAR(45) NULL,
  `adres_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Paczkomaty_adres1_idx` (`adres_id` ASC),
  CONSTRAINT `fk_Paczkomaty_adres1`
    FOREIGN KEY (`adres_id`)
    REFERENCES `militaria`.`adres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `militaria`.`zamowienie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `militaria`.`zamowienie` (
  `id` INT NOT NULL,
  `numer_zamowenia` VARCHAR(45) NULL,
  `Paczkomaty_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_zamowienie_Paczkomaty1_idx` (`Paczkomaty_id` ASC),
  CONSTRAINT `fk_zamowienie_Paczkomaty1`
    FOREIGN KEY (`Paczkomaty_id`)
    REFERENCES `militaria`.`Paczkomaty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `militaria`.`historia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `militaria`.`historia` (
  `id` INT NOT NULL,
  `data` DATETIME NULL,
  `zamowienie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historia_zamowienie1_idx` (`zamowienie_id` ASC),
  CONSTRAINT `fk_historia_zamowienie1`
    FOREIGN KEY (`zamowienie_id`)
    REFERENCES `militaria`.`zamowienie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `militaria`.`zamowienie_has_produkt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `militaria`.`zamowienie_has_produkt` (
  `zamowienie_id` INT NOT NULL,
  `produkt_id` INT NOT NULL,
  PRIMARY KEY (`zamowienie_id`, `produkt_id`),
  INDEX `fk_zamowienie_has_produkt_produkt1_idx` (`produkt_id` ASC),
  INDEX `fk_zamowienie_has_produkt_zamowienie1_idx` (`zamowienie_id` ASC),
  CONSTRAINT `fk_zamowienie_has_produkt_zamowienie1`
    FOREIGN KEY (`zamowienie_id`)
    REFERENCES `militaria`.`zamowienie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zamowienie_has_produkt_produkt1`
    FOREIGN KEY (`produkt_id`)
    REFERENCES `militaria`.`produkt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
